apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "TestApplication"
  description: "Test"
  labels:
    system: web-apps
  links:
    - url: https://github.com/ItRachii/testapplication
      title: "TestApplication"
      icon: code
  tags:
    - java
    - "applicationtype-webapplication"
  annotations:
    jenkins.io/github-folder: testapplication/undefined
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ItRachii/testapplication
    sonarqube.org/project-key: 'JtSpringProject/rachit'
    prometheus.io/rules: 
spec:
  type: service
  lifecycle: development
  owner: "user:default/neelesh.shekhar"
  ownerEmail: 
